name: Docs CI

on:
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint.json'
      - '.github/workflows/docs-ci.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint '**/*.md' -c .markdownlint.json || true

      - name: Install lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --exclude-mail --accept 429 '**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}